### ISSUE TITLE
附魔显示错误，基岩版附魔需要等级计算错误

### ISSUE THREAD

**Issue by 1143910315** [Dinosaur-MC/BestEnchSeq#11]
无论是java版还是基岩版，初始装备选择耐久2时，再选择附魔到耐久3，界面显示耐久2
基岩版情况下，计算的需要经验值是2，实际应为1

**Comment by 1143910315** [comment]
![QQ20241011-171347](https://github.com/user-attachments/assets/329a751f-db9b-40f7-b246-f1b00401cf45)

**Comment by 1143910315** [comment]
基岩版应该是（耐久3-耐久2）*来自书的乘数=>(3-2)*1=1

**Comment by Dinosaur-MC** [comment]
1. 魔咒显示无误，只是计算流程种不显示最终合成结果。
2. 基岩版附魔花费等级计算错误：计算模块BUG。

**Comment by 1143910315** [comment]
可是界面+号右边难道不是应该是显示耐久3吗

**Comment by 1143910315** [comment]
![QQ20241011-200628](https://github.com/user-attachments/assets/e56a9a13-985e-455e-9b7f-1bc4d4a17363)

**Comment by 1143910315** [comment]
那这个呢，效率变成5级了，耐久还是1级

**Comment by Dinosaur-MC** [comment]
> ![QQ20241011-200628](https://private-user-images.githubusercontent.com/20817444/375747230-e56a9a13-985e-455e-9b7f-1bc4d4a17363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDg5NDcsIm5iZiI6MTcyODY0ODY0NywicGF0aCI6Ii8yMDgxNzQ0NC8zNzU3NDcyMzAtZTU2YTlhMTMtOTg1ZS00NTVlLTliN2YtMWJjNGQ0YTE3MzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEyMTA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNzEzNmU3MWQwODY3MGRkNWM0MWNhMjY2ZmI1NjA1OGFkZjUxNjIwNmM0MWQxODY3MTNkMTBlMDY3MjZiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7yc5v_R-EFMT0CSdvY4xNxE_BvBNc3UOSvWAcHbD9Qg)

这看起来是个问题，不过注意到你开启了自定义魔咒相关的功能，尝试关闭后再试试？

**Comment by Dinosaur-MC** [comment]
基岩版计算附魔错误的BUG已在 c2fd797c000155d60a9eaf2440b57d19e83e0be9 中修复。

**Comment by 1143910315** [comment]
关了，结果一样。这个基岩版等级计算不正确和显示附魔等级问题，我用一年前的版本就有了（因为基岩版附魔可以找村民买带一部分附魔的工具来降低经验值消耗），突然发现这个仓库有更新了，才来提的

**Comment by 1143910315** [comment]
我其实会来看仓库，是因为我用c++写完了铁砧附魔的穷举算法。
穷举算法能找到比这两个算法更省经验值的路线，虽然我写这个主要还是为了自定义附魔。
我都实现完了，才发现原来已经支持自定义附魔了（悲）

**Comment by Dinosaur-MC** [comment]
> 关了，结果一样。这个基岩版等级计算不正确和显示附魔等级问题，我用一年前的版本就有了（因为基岩版附魔可以找村民买带一部分附魔的工具来降低经验值消耗），突然发现这个仓库有更新了，才来提的

这个项目的main分支的代码已经好久了，而且是当时初学C++和Qt的时候作为练习写写的，所以现在不好维护，近段时间的更新基本都是小修小补，大更新要等下一个重构版本。

**Comment by Dinosaur-MC** [comment]
> 我其实会来看仓库，是因为我用c++写完了铁砧附魔的穷举算法。 穷举算法能找到比这两个算法更省经验值的路线，虽然我写这个主要还是为了自定义附魔。 我都实现完了，才发现原来已经支持自定义附魔了（悲）

第一个release起就支持自定义魔咒了，我前一段时间也写完了一个C++的穷举，打算写一个BESQ-Core-CLI，但是还没有空写完全部功能，就没有发布。

**Comment by Dinosaur-MC** [comment]
所有问题已在 13c42ecc844f527dc1a16346fa8dbe6a452e892b 中修复。
