### ISSUE TITLE
程序无法启动：无法定位程序输入点CreateEventW于动态链接库api-ms-core-synch-l1-2-0.dll上

### ISSUE THREAD

**Issue by Dinosaur-MC** [Dinosaur-MC/BestEnchSeq#3]
程序启动时报错“无法定位程序输入点CreateEventW于动态链接库api-ms-win-core-synch-l1-2-0.dll上”，导致程序无法启动。
已发现的问题复现环境：Windows 7 SP0，Windows 7 SP1。

**Comment by Chen-Junren** [comment]
试试CMD命令：

1. Dism /Online /Cleanup-Image /ScanHealth
2. Dism /Online /Cleanup-Image /CheckHealth
3. DISM /Online /Cleanup-image /RestoreHealth
4. sfc /SCANNOW

**需要管理员权限**

**Comment by Dinosaur-MC** [comment]
已发现问题在Qt5中能够得到解决（Qt6已不再支持Windows7及更早的Windows操作系统），但若无特殊必要需求则这里不会提供在Qt5上的软件版本，即不支持Windows7及更早的Windows操作系统，要使用本软件请更新至Windows10或更新的Windows操作系统。
