### ISSUE TITLE
程序报错：无法正确解析JSON文件；版本：2.0.1Bata

### ISSUE THREAD

**Issue by HXYMCH** [Dinosaur-MC/BestEnchSeq#4]
不会对正常使用产生过大影响，建议修一下awa

**Comment by HXYMCH** [comment]
谢谢大佬

**Comment by Dinosaur-MC** [comment]
这个属于更新检查模块的报错，通常是因为程序无法正常连接到更新服务器（本仓库）导致的，一般可以通过一些加速手段对github.com进行加速来解决这个问题，而不能在软件中直接解决（除非软件捆绑加速器）。

**Comment by HXYMCH** [comment]
Ok,我下载了一个加速器,已经能用了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年8月7日 15:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Dinosaur-MC/BestEnchSeq] 程序报错：无法正确解析JSON文件；版本：2.0.1Bata (Issue #4)


这个属于更新检查模块的报错，通常是因为程序无法正常连接到更新服务器（本仓库）导致的，一般可以通过一些加速手段对github.com进行加速来解决这个问题，而不能在软件中直接解决（除非软件捆绑加速器）。

―
