### ISSUE TITLE
更新魔咒请求

### ISSUE THREAD

**Issue by rlbkl** [Dinosaur-MC/BestEnchSeq#8]
什么时候更新魔咒 迅捷潜行3 谢谢你了

**Comment by Dinosaur-MC** [comment]
迅捷潜行从 dfba0db161a6ce367c89c0c186c7b08fc5b6f958 就有了，如果你的软件里没有，请更新至[最新版本](https://github.com/Dinosaur-MC/BestEnchSeq/releases/latest)。
